### ISSUE TITLE
minimize sidebar without clicking button

### ISSUE THREAD

**Issue by areanto** [creativetimofficial/material-dashboard-pro#106]
How to activate the minimize sidebar function  in every page without clicking the button ?
thx

**Comment by dragosct10** [comment]
Hi, @areanto! You can put on the `body` tag the class `.sidebar-mini`. 

Regards,
Dragos

**Comment by areanto** [comment]
wow!
Thank you so much for your fast answer.
It works

**Comment by ruinunes** [comment]
Granted, this works nice if we are loading the html with the class already set on the markup.
But I'm having trouble adding this class afterwards on `$(document).ready`, because for a split second - while querying some kind of client-side state [like localStorage] to see if we should start the page with the `sidebar-mini` class in the first place - the page will appear with the expanded look and then animate to the state given by `sidebar-mini`, which is not workable for me. I need a way to query the state fast enough to display the proper minimized look or to avoid the transition animation from expanded to mini.

Does anyone have interesting solution? or is there anything baked in the theme somewhere already?

**Comment by alexandru-paduraru** [comment]
@ruinunes maybe a preloader will help, you put some "loading" on the page, you do the backend stuff and when that is finished you just show the dashboard to the user, check this: https://github.com/niklausgerber/PreLoadMe
