### ISSUE TITLE
Icon Header is now truncated

### ISSUE THREAD

**Issue by jsmith-phoenix** [creativetimofficial/material-dashboard-pro#137]
Hello, I've been using the Material-UI dashboard and been very happy with it. Starting yesterday I started to see the Headers on the Cards (Ex: IconCard, ProfileCard) get visually cut off at the top of the panel. They no longer appear offset off the top.

I don't believe that I've changed anything that would impact this.

![image](https://user-images.githubusercontent.com/24377680/39401055-adc774b8-4b0a-11e8-9912-680b209309a8.png)

Any thoughts? I've retired reverting to an older version of the material-ui beta but that didn't seem to have an effect.

**Comment by dragosct10** [comment]
Hi, @jsmith-phoenix! Thank you for using our product. I noticed that in our part the headers icon are overflowing well, please give us your link to see what is the problem. Regards, Dragos

**Comment by jsmith-phoenix** [comment]
thanks @dragosct10 . Examples are at:
http://54.173.60.30/pages/lock-screen-page
http://54.173.60.30/pages/goodbye-page

**Comment by dragosct10** [comment]
Hi, @jsmith-phoenix! The problem is that you have `overflow: hidden;` on the card so this is not ok. You must remove it to fix the problem. 

<img width="1280" alt="screen shot 2018-05-04 at 10 30 38" src="https://user-images.githubusercontent.com/17456857/39616915-5834cf70-4f86-11e8-9f33-88670a0433d6.png">

Regards,
Dragos

**Comment by jsmith-phoenix** [comment]
Thanks for the pointer Dragos. I'm not sure why the MuiCard changed on me. I've overridden it in the style and that's addressed it.
