### ISSUE TITLE
Datetime Picker bad month return

### ISSUE THREAD

**Issue by moose75** [creativetimofficial/material-dashboard-pro#22]
When clicking on a date before or after the current selected month (greyed days), the datetime picker should return the right month along the day number. It's the way jquery and other datetime pickers works.
Thanks in advance !
PS/ see screen capture below ...

**Comment by moose75** [comment]
![datetime picker bug 1](https://cloud.githubusercontent.com/assets/3322407/24070838/1fc50c82-0bc5-11e7-973e-ee1b94f8dcac.jpg)
![datetime picker bug 2](https://cloud.githubusercontent.com/assets/3322407/24070840/251024f6-0bc5-11e7-942a-1fc8a848b9e8.jpg)

**Comment by MysticEarth** [comment]
Encountered the same problem as well, we're using `Material Dashboard Pro v1.0.0`

**Comment by dragosct10** [comment]
I will attach below a file that will fix the bug with datetimepicker. The partial` _plugin-datetime-picker.scss` must be replaced in `assets/scss/material-dashboard/plugins/_plugin-datetime-picker.scss` with the new file over the old one, then after you replace please compile your scss with [Koala](http://koala-app.com/). After you do that everything I think will be ok! Best, Dragos!

[_plugin-datetime-picker.scss.zip](https://github.com/creativetimofficial/material-dashboard-pro/files/861662/_plugin-datetime-picker.scss.zip)

**Comment by MysticEarth** [comment]
@dragosct10 what exactly does your changes do? It seems to me this particular bug doesn't relate to any CSS, but just JavaScript instead.

**Comment by fvox13** [comment]
I ran into this bug too.  It stems from the Creative Tim modifications to the datetimepicker; specifically, the added `<div>` tags added near these comments `Creative Tim - we added a div inside each td for design purposes`.  If you remove the extra `<div>` or overwrite the plugin with the vanilla version from the original plugin author, the dates work as expected, but the calendar doesn't look correct, since that `<div>` is being used for `design purposes` as the comment indicates.

It appears that the plugin is expecting to get *just* the number you clicked on, but with the extra `<div>` it is getting the number, wrapped in a `<div>`, which it's unable to cope with.

**Comment by dragosct10** [comment]
Hi @MysticEarth! The JavaScript of this plugin its working good. The problem it seems to be on css because if you notice in the image that I uploaded the circle coloured div which is active day must be under the `td` div because javascript of this plugin will act only on click to `td` div, so this  `td` div must to be over the circle coloured div not at the same level.  

![Uploading Screen Shot 2017-03-22 at 16.55.53.png…]()

**Comment by fvox13** [comment]
@dragosct10 the `div` that's adding the coloured circle is the problem.  If you remove it, the picker works as designed, which is the behavior reported in this bug.  That `div` was added by Creative Tim, so I'm hoping they have a fix.

**Comment by fvox13** [comment]
Note that this bug is not present in the upstream package:
https://eonasdan.github.io/bootstrap-datetimepicker/

**Comment by dragosct10** [comment]
@fvox13 I'm part of the Creative Tim team and this will be an official fix. Thank you for pointing out!

**Comment by fvox13** [comment]
Thanks, @dragosct10 !

**Comment by moose75** [comment]
@dragosct10 Thanks for the kick fix, I've applied the patch and it Datetime Picker works now as expected. 

@fvox13 the .css changes consist of adding the 3 last parameters ...

.bootstrap-datetimepicker-widget table td.day > div {
  height: 30px;
  line-height: 30px;
  width: 30px;
  text-align: center;
  padding: 0px;
  border-radius: 50%;
  **_margin: 0 auto;
  z-index: -1;
  position: relative;_**
