### ISSUE TITLE
Visualization problem with navbar fixed and sidebar mini

### ISSUE THREAD

**Issue by andres770105** [creativetimofficial/material-dashboard-pro#23]
Following instructions in https://github.com/creativetimofficial/material-dashboard-pro/issues/15, remains a visualization problem when I´m activating sidebar mini, the navbar width doesn´t resizes.

Thanks in advance.

![navbar-fixed error](https://cloud.githubusercontent.com/assets/26516246/24078530/f2bad54a-0c3d-11e7-9724-b562468c9eaf.jpg)

**Comment by andres770105** [comment]
Solved by myself... Just add to "/assets/sass/material-dashboard/_sidebar-and-main-panel.scss" (v1.1.0) the following code, after line 740:

        .navbar {
            width: calc(100% - 80px);
            margin-left: 80px;
        }

Next, you must compile you Scss with Koala.

That's all, enjoy it!

**Comment by alexandru-paduraru** [comment]
@andres770105 yes, you're right, on #15 the changes are working only for the full sidebar, because we referred to that solution from the Free Material Dashboard (which doesn't have the sidebar-mini). For the sidebar-mini in the PRO version, you need your solution. Congrats for it :D 

We will add it in the next update.

Best,
Alex
