### ISSUE TITLE
Firefox 52.0.2: Highlight positioning problem checkbox click animation

### ISSUE THREAD

**Issue by SuperDaifuku** [creativetimofficial/material-dashboard-pro#28]
Hi,
there seems to be a problem with the positioning of the highlight, when you click a checkbox. The highlight is off centered. You can reproduce it on your demo page:
http://demos.creative-tim.com/material-dashboard-pro/examples/forms/regular.html

I'm pretty sure it's because of the recent Firefox update, because it worked few days ago. In Chrome everything is fine.

**Comment by dragosct10** [comment]
Hi @SuperDaifuku! We've checked the issue that you have with checkboxes on Firefox and a simple way to fix this issue is to add on `::before` of the element `<span class="checkbox-material"></span>` property `top` with `-7px`. We already made this for you and I will attach on the bottom the link with scss partial `_checkboxes.scss`. All you need to do is to replace this file with the old one and then you must compile you scss with [Koala](http://koala-app.com/). I hope that will help you! Please tell us if everything is ok! 

[_checkboxes.scss.zip](https://github.com/creativetimofficial/material-dashboard-pro/files/890389/_checkboxes.scss.zip)


Thanks,
Dragos

**Comment by SuperDaifuku** [comment]
awesome! fixed the problem
thank you :)
